### ISSUE TITLE
Garmin authentication fails

### ISSUE THREAD

**Issue by jschram** [magnific0/nokia-weight-sync#16]
Garmin authentication fails:
```
garmin.APIException: Unable to retrieve username: 'NoneType' object has no attribute 'group' (user <garmin.UserException object at 0x7f3f8cacfe10> )
```

Fixed with this PR: [Fix Garmin signin URLs, synced from cpfair/tapiriik #15 ](https://github.com/magnific0/nokia-weight-sync/pull/15)

**Comment by nurps** [comment]
thx, working fine again
