### ISSUE TITLE
Error upon connecting to Garmin

### ISSUE THREAD

**Issue by jschram** [magnific0/nokia-weight-sync#3]
After configuring, the sync from Nokia to Garmin fails. (Since I see an error about APIException not being defined, I've added the exception as print() as well):

```Last weight from Nokia Health: ##### kg taken at 2018-04-09T05:36:34+00:00
GC redeem-start error 503 <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

Traceback (most recent call last):
  File "./nokia-weight-sync.py", line 268, in <module>
    session = garmin.login(config.get('garmin','username'), config.get('garmin','password'))
  File "/Volumes/Code/nokia-weight-sync/garmin.py", line 135, in login
    session = self._get_session(email=username, password=password)
  File "/Volumes/Code/nokia-weight-sync/garmin.py", line 96, in _get_session
    raise APIException("GC redeem-start error %s %s" % (gcRedeemResp.status_code, gcRedeemResp.text))
NameError: name 'APIException' is not defined```

Did Garmin perhaps change their endpoints?

**Comment by magnific0** [comment]
@jschram thanks for reporting this issue. I am experiencing it too. Unfortunately it seems that something has changed on Garmin's side. I'll look into to this problem and see whether it can be resolved, but that will probably only happen later this week.

**Comment by magnific0** [comment]
@jschram I just had a quick look and it seems indeed Garmin's end that changed. However, the people over at tapiriik [were already on top of this](https://github.com/cpfair/tapiriik/commit/656bb2066f9b753c2e3e87a66bef38d21c21c63b), so it was straight forward for me to copy these changes. 

So the problem should be fixed now. Can you pull the latest code and let me know if it works for you too?

**Comment by jschram** [comment]
Thanks for your quick response @magnific0, it's successfully syncing now. 👍
