### ISSUE TITLE
Logo doesn't conform to Nokia requirements

### ISSUE THREAD

**Issue by fernat** [magnific0/nokia-weight-sync#6]
The provided logo doesn't meet Nokia's requirements:

The image must be greater than 256x256
The image size must not be more than 300 ko
The image format must be .png or .jpg
The image ratio must be a square
Background image must be white

Can you edit so I can use your logo?

**Comment by magnific0** [comment]
I just uploaded a scaled up version with a white background to the repository:
https://github.com/magnific0/nokia-weight-sync/blob/master/logo256w.png
